version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16-browsers
        environment:
          CHROME_REVISION: 652421
          CHROMEDRIVER_VERSION: 75.0.3770.90
          
    steps:
      - checkout
      
      - restore_cache:
          key: node_modules-{{ .Branch }}-{{ checksum "package-lock.json" }}

      - run:
          name: NPM Install
          command: |
            npm i
            cd testapp && npm i
      - save_cache:
          key: node_modules-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
            - "testapp/node_modules"

      - run:
          name: Lint
          command: ./node_modules/.bin/gulp lint

      - run:
          name: Selenium Start
          background: true
          command: |
            ./node_modules/.bin/webdriver-manager update --versions.standalone=3.141.59 --versions.chrome=${CHROMEDRIVER_VERSION} --versions.gecko=v0.26.0
            sudo cp ./node_modules/webdriver-manager/selenium/chromedriver_${CHROMEDRIVER_VERSION} /usr/local/bin/chromedriver
            ./node_modules/.bin/webdriver-manager start --versions.standalone=3.141.59 --versions.chrome=${CHROMEDRIVER_VERSION} --versions.gecko=v0.26.0
      - run:
          name: TestApp Start
          background: true
          command: |
            npm start
      - run:
          name: Test
          command: npm test