version: 2.1
orbs:
  node: circleci/node:8-browsers #circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run test -- --watch=false --progress=false --browsers=ChromeHeadlessCI
            - run: npm run e2e -- --protractor-config=./e2e/protractor-ci.conf.js

workflows:
    build-and-test:
      jobs:
        - build-and-test