version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  test:
    working_directory: ~/adc-front
    docker:
      - image: 'circleci/node:12-browsers'

    steps:
      - checkout
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
         
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
                
      - run:
          name: Install local dependencies
          command: npm install

      - run : 
          name: Install Karma and Chrome-launcher
          command: npm install karma karma-chrome-launcher
               
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
                  
      - run:
          name: Testing
          command: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
               
      - run:
          name: End to End Test
          command: npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js

workflows:
        version: 2
        # the test workflow
        test_workflow:
            jobs:
                - test

